kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hello-java-spring-boot
  namespace: omkar
  uid: 278be3ad-25ce-498f-8481-a5b937e94e04
  resourceVersion: '780454'
  generation: 3
  creationTimestamp: '2024-03-18T07:04:37Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2024-03-18T07:42:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:sourceStrategy':
              .: {}
              'f:from': {}
            'f:type': {}
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: omkar
        name: 'hello-java-spring-boot:v1.0'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/monodot/hello-java-spring-boot/'
    contextDir: /
  runPolicy: Serial
status:
  lastVersion: 0
